babelfish-for-postgresql/babelfish_compass

- UserGuide.md
... tracking the change made in 35919996
[Describe what this change achieves]
[List any issues this PR will resolve]
> Update download location in UserGuide.md

- README.md
Add workflow, license, and version badges to README
n/a
> Add workflow, license, and version badges

- .github/workflows/release.yml
Give permissions to Release workflow
n/a
> Give permissions to Release workflow

- BabelfishFeatures.cfg
- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassConfig.java
- src/main/java/compass/CompassUtilities.java
Fixes to Mac/Linux support
Fixes to general file handling on Mac/Linux; implementation of -pgimport on Mac/Linux
> improved Mac/Linux support

- src/main/java/compass/CompassUtilities.java
Added checks against code injection with -pgimport
check for statement delimiters in -pgimport arguments
> check for code injection with -pgimport

- BabelfishFeatures.cfg
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
Report better info for DDL triggers and DB/server roles. Fix HTML reporting.
Report better info for DDL triggers and DB/server roles. Fix HTML reporting.
> better info for roles, DDL triggers; HTML fixes

- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassConfig.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLLexer.g4
- src/main/parser/TSQLParser.g4
v1.2 of Babelfish Compass
Changes in v1.2:
- minor grammar fixes
- new -rewrite feature
- fixed bug with -importonly
- capture files are now versioned
- various small fixes
> v1.2, -rewrite feature

- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
incorporate feedback from Tibor on -rewrite
- mark each rewritten part with a tag
- retain original file type suffix 
- additional rewrite cases
> incorporated feedback from Tibor on -rewrite

- BabelfishFeatures.cfg
- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLParser.g4
Detect DML as table source
Detect DML as table source (INSERT-SELECT FROM (DML-with-OUTPUT)
> detect DML as table source

- src/main/java/compass/Compass.java
- src/main/java/compass/CompassUtilities.java
pgimport fix
pgimport fix - did not work when using latest BBF version
preparation for allowing anonymized analysis feedback
- [ x] Commits are signed per the DCO using --signoff 
> pgimport fix

- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLLexer.g4
- src/main/parser/TSQLParser.g4
Grammar fixes & reporting fixes
- grammar fixes for nested RETURN in UDFs
- grammar fixes for ALTER PARITION
- ABORT can be a keyword
- small reporting fixes
- fixed lookup of identifiers with embedded special chars
- in xref, add list of object names with/without issues
- [ x] Commits are signed per the DCO using --signoff 
> small grammar fixes, reporting fixes

- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
support ALTER TABLE..ADD with -rewrite
- support rewriting of ALTER TABLE..ADD for multiple added items
- upgrade older report directories to use html subdir
- [ x] Commits are signed per the DCO using --signoff 
> support ALTER TABLE..ADD with -rewrite

- src/main/java/compass/CompassUtilities.java
changes to comments
Only changes to some comments
- [x ] Commits are signed per the DCO using --signoff 
> changes to comments

- README.md
Added a note about Compass v1.2 to the README file
Added a note about Compass v1.2 to the README file
- [ x] Commits are signed per the DCO using --signoff 
> README update for v1.2

- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
fixes to MERGE/WAITFOR rewrite
- fix for MERGE rewrite
- support WAITFOR DELAY rewrite when there's no string constant argument
- better reporting of delimited proc names and cross-db proc calls
- [x ] Commits are signed per the DCO using --signoff 
> fixes to MERGE/WAITFOR rewrite

- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassConfig.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLLexer.g4
- src/main/parser/TSQLParser.g4
- src/test/java/compass/CompassTest.java
various enhancements
- better reporting of cross-DB and remote object references, GRANT/REVOKE, geospatial features; presentation improvements
- fixed reporting of identifier containing invalid characters 
- various grammar improvements 
- fix for UTF8-with-BOM input files
- preparing for Babelfish v.1.2.0
> various enhancements

- CHANGELOG.md
- Updating CHANGELOG.md for Upcoming Babelfish v1.2.0
Signed-off-by: Matthew Hsu <hsmatthe@amazon.com>
> docs: Update CHANGELOG.md for Upcoming Babelfish v1.2.0

- CHANGELOG.md
- Updating CHANGELOG.md for Compass 2022-03-a Release
Signed-off-by: Matthew Hsu <hsmatthe@amazon.com>
> docs: Update CHANGELOG.md for Compass 2022-03-a Release

- BabelfishCompassUser.Optimistic.cfg
Adding file BabelfishCompassUser.Optimistic.cfg
abelfishCompassUser.Optimistic.cfg needs to be in the .zip file for each new distro
> added BabelfishCompassUser.Optimistic.cfg

- CHANGELOG.md
modify CHANGELOG for 2023-06
modify CHANGELOG for 2023-06
> modify CHANGELOG for 2023-06

- BabelfishCompassUser.Optimistic.cfg
- BabelfishFeatures.cfg
- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLParser.g4
Small fixes and enhancements
- allow LABEL as identifier
- identify and report converting DATETIME to numeric
- identify and report IF/ELSE branches containing only DECLARE
- rewrite fix for missing AS keyword in some cases of CREATE FUNCTION
- small fixes to user .cfg file handling and rewriting
> small fixes and enhancements

- BabelfishCompassUser.Optimistic.cfg
- BabelfishFeatures.cfg
- src/main/java/compass/Compass.java
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
- src/main/parser/TSQLLexer.g4
- src/main/parser/TSQLParser.g4
update to 2023-06 
- report/rewrite PG operators =@@/>@@ which require a space, like in `WHERE spid=@@spid`
- report ESCAPE with LIKE operator
- report use of TOP(subquery) for INSERT/UPDATE/DELETE
- report sqlcmd commands and scripting variables
> v.2023-06 additional updates

- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
Fix long fields in pgimport
Fix long fields in pgimport
> Fix long fields in pgimport

- src/main/java/compass/CompassUtilities.java
Update Compass version to 2024-10
Update Compass version to 2024-10
> Update Compass version to 2024-10

- CHANGELOG.md
- src/main/java/compass/CompassUtilities.java
Detect and rewrite redundant unary '+' operators for strings.
Detect and rewrite redundant unary '+' operators for strings.
> unary + handling

- .github/workflows/release.yml
Add user guide to distro .zip file
Add user guide to distro .zip file
> Add user guide to distro .zip file

- BabelfishFeatures.cfg
- src/main/java/compass/CompassAnalyze.java
- src/main/java/compass/CompassUtilities.java
Report legacy schema names
Report legacy schema names, now that some fixed DB roles are supported.
Minor changes to the reporting for some fulltext-search features.
> Report legacy schema names

- src/test/java/test07feb.txt
- src/test/java/testdir07feb/test07feb.txt
> test07feb add file/dir

- src/test/java/test07feb.txt
- src/test/java/testdir07feb/test07feb.txt
> test remove files
